fix: llama-stack-api packaging
fix a few things up, currently if you `pip install llama-stack-api` by itself, importing it breaks:

```
python3.13
Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_stack_api
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import llama_stack_api
ModuleNotFoundError: No module named 'llama_stack_api'
>>>
```

changing the setupools package loc to ".." fixes this, but then:

```
python3.13
Python 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_stack_api
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import llama_stack_api
  File "/Users/charliedoern/projects/Documents/llama-stack/src/llama_stack_api/__init__.py", line 41, in <module>
    from .batches import (
    ...<7 lines>...
    )
  File "/Users/charliedoern/projects/Documents/llama-stack/src/llama_stack_api/batches/__init__.py", line 14, in <module>
    from openai.types import Batch as BatchObject
ModuleNotFoundError: No module named 'openai'
>>>
```

so openai needs to also be added as a dependency

this should be backported and released for 0.4.z

Signed-off-by: Charlie Doern <cdoern@redhat.com>